github:
  description: "Apache NuttX Testing contains NTFC test cases for Apache NuttX RTOS"
  homepage: https://nuttx.apache.org/
  features:
    # Enable issues management
    issues: true
    # Enable project for project management boards
    projects: true
  labels:
    - nuttx
    - rtos
    - embedded
    - real-time
    - mcu
    - microcontroller
    - ci
    - ntfc
    - pytest
  enabled_merge_buttons:
    # disable squash button:
    squash:  false
    # disable merge button:
    merge:   false
    # enable rebase button:
    rebase:  true
